/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAcervoRouteImport } from './routes/_app.acervo'
import { Route as AppAlertasRouteImport } from './routes/_app.alertas'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppIdeiasRouteImport } from './routes/_app.ideias'
import { Route as AppKanbanRouteImport } from './routes/_app.kanban'
import { Route as AppAcervoIndexRouteImport } from './routes/_app.acervo.index'
import { Route as AppAcervoAtasRouteImport } from './routes/_app.acervo.atas'
import { Route as AppAcervoMuralRouteImport } from './routes/_app.acervo.mural'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcervoRoute = AppAcervoRouteImport.update({
  id: '/acervo',
  path: '/acervo',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeiasRoute = AppIdeiasRouteImport.update({
  id: '/ideias',
  path: '/ideias',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppAcervoIndexRoute = AppAcervoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAcervoRoute,
} as any)
const AppAcervoAtasRoute = AppAcervoAtasRouteImport.update({
  id: '/atas',
  path: '/atas',
  getParentRoute: () => AppAcervoRoute,
} as any)
const AppAcervoMuralRoute = AppAcervoMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AppAcervoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/acervo': typeof AppAcervoRouteWithChildren
  '/alertas': typeof AppAlertasRoute
  '/config': typeof AppConfigRoute
  '/ideias': typeof AppIdeiasRoute
  '/kanban': typeof AppKanbanRoute
  '/acervo/atas': typeof AppAcervoAtasRoute
  '/acervo/mural': typeof AppAcervoMuralRoute
  '/acervo/': typeof AppAcervoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/config': typeof AppConfigRoute
  '/ideias': typeof AppIdeiasRoute
  '/kanban': typeof AppKanbanRoute
  '/': typeof AppIndexRoute
  '/acervo/atas': typeof AppAcervoAtasRoute
  '/acervo/mural': typeof AppAcervoMuralRoute
  '/acervo': typeof AppAcervoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/acervo': typeof AppAcervoRouteWithChildren
  '/_app/alertas': typeof AppAlertasRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/ideias': typeof AppIdeiasRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/': typeof AppIndexRoute
  '/_app/acervo/atas': typeof AppAcervoAtasRoute
  '/_app/acervo/mural': typeof AppAcervoMuralRoute
  '/_app/acervo/': typeof AppAcervoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/acervo'
    | '/alertas'
    | '/config'
    | '/ideias'
    | '/kanban'
    | '/acervo/atas'
    | '/acervo/mural'
    | '/acervo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alertas'
    | '/config'
    | '/ideias'
    | '/kanban'
    | '/'
    | '/acervo/atas'
    | '/acervo/mural'
    | '/acervo'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/acervo'
    | '/_app/alertas'
    | '/_app/config'
    | '/_app/ideias'
    | '/_app/kanban'
    | '/_app/'
    | '/_app/acervo/atas'
    | '/_app/acervo/mural'
    | '/_app/acervo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acervo': {
      id: '/_app/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof AppAcervoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideias': {
      id: '/_app/ideias'
      path: '/ideias'
      fullPath: '/ideias'
      preLoaderRoute: typeof AppIdeiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acervo/': {
      id: '/_app/acervo/'
      path: '/'
      fullPath: '/acervo/'
      preLoaderRoute: typeof AppAcervoIndexRouteImport
      parentRoute: typeof AppAcervoRoute
    }
    '/_app/acervo/atas': {
      id: '/_app/acervo/atas'
      path: '/atas'
      fullPath: '/acervo/atas'
      preLoaderRoute: typeof AppAcervoAtasRouteImport
      parentRoute: typeof AppAcervoRoute
    }
    '/_app/acervo/mural': {
      id: '/_app/acervo/mural'
      path: '/mural'
      fullPath: '/acervo/mural'
      preLoaderRoute: typeof AppAcervoMuralRouteImport
      parentRoute: typeof AppAcervoRoute
    }
  }
}

interface AppAcervoRouteChildren {
  AppAcervoAtasRoute: typeof AppAcervoAtasRoute
  AppAcervoMuralRoute: typeof AppAcervoMuralRoute
  AppAcervoIndexRoute: typeof AppAcervoIndexRoute
}

const AppAcervoRouteChildren: AppAcervoRouteChildren = {
  AppAcervoAtasRoute: AppAcervoAtasRoute,
  AppAcervoMuralRoute: AppAcervoMuralRoute,
  AppAcervoIndexRoute: AppAcervoIndexRoute,
}

const AppAcervoRouteWithChildren = AppAcervoRoute._addFileChildren(
  AppAcervoRouteChildren,
)

interface AppRouteChildren {
  AppAcervoRoute: typeof AppAcervoRouteWithChildren
  AppAlertasRoute: typeof AppAlertasRoute
  AppConfigRoute: typeof AppConfigRoute
  AppIdeiasRoute: typeof AppIdeiasRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcervoRoute: AppAcervoRouteWithChildren,
  AppAlertasRoute: AppAlertasRoute,
  AppConfigRoute: AppConfigRoute,
  AppIdeiasRoute: AppIdeiasRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
